name: Build and Deploy
on: repository_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Run builds and deploys with ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and deploy
      env:
        GATSBY_API: ${{ secrets.GATSBY_API }}
        GA_TID: ${{ secrets.GA_TID }}
      run: |
        npm i -D
        npm run build
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: ${{ secrets.SOURCE }}
        target: ${{ secrets.TARGET }}
